name: book_store_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.7.0
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  go_router: ^6.5.5
  url_strategy: ^0.2.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  animated_conditional_builder: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMMono
      fonts:
        - asset: assets/fonts/dm_mono/DMMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_mono/DMMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/dm_mono/DMMono-Light.ttf
          weight: 300

    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/DmSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DmSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DmSans-Regular.ttf
          weight: 400


